version: '3.3'

services:
  apache:
    image: 'php:7.2-apache'
    container_name: caldeiraseit2-php
    restart: always
    ports:
      - '8080:81'
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: caldeiraseit2-mysql
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=caldeiraseit-mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
  phpmyadmin:
    container_name: caldeiraseit2-myadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysqldb
    ports:
      - 9191:80
    environment:
      PMA_HOST: mysqldb